version: '3'
services:
  server:
    image: app:build
    depends_on:
      - db
    ports:
      - "8000:8000"
    user: app
    volumes:
      - .:/app
    command: dev
    links:
      - db
    env_file:
      - .env

  worker:
    image: app:build
    env_file: .env
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    volumes:
      - .:/app
    command: worker

  beat:
    image: app:build
    env_file: .env
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    volumes:
      - .:/app
    command: beat

  db:
    image: postgres:9.5-alpine
    logging:
      driver: "none"

  redis:
    image: redis:5.0.5-alpine
